name: Memory Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  asan:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, name: linux-x64 }
          - { os: ubuntu-24.04-arm, name: linux-arm64 }
    name: asan (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run AddressSanitizer + UBSan + LeakSanitizer
        run: make asan

  valgrind:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { os: ubuntu-24.04, name: linux-x64 }
          - { os: ubuntu-24.04-arm, name: linux-arm64 }
    name: valgrind (${{ matrix.name }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Run Valgrind
        run: make valgrind
